Traceback (most recent call last):
  File "main.py", line 154, in <module>
  File "main.py", line 149, in main
  File "main.py", line 33, in __init__
  File "main.py", line 95, in initView
  File "source\terminal.pyo", line 42, in __init__
KeyError: 'c_help'
